"""v1：正面银虎斑美短。圆脸金眼、额头 M 纹。"""

from __future__ import annotations

from rich.text import Text

from cli.tui.icons.spec import Icon
from cli.tui.icons.sprite import render_sprite

# . 空  k 线  s 银毛  t 虎斑  i 耳内灰  g 金虹膜  u 瞳  h 高光  n 鼻  m 嘴
SPRITE = """
..............kkkk............kkkk..............
.............kiiiik..........kiiiik.............
............kisssskk........kkssssik............
...........kssssssskkkkkkkkkksssssssk...........
..........kssssssssssssssssssssssssssk..........
.........kssssssssssssssssssssssssssssk.........
........kssssssssssstssstssstssssssssssk........
.......kssssssssssssststststssssssssssssk.......
.......ksssssssssssssstssstsssssssssssssk.......
......kssssssssssssssssssssssssssssssssssk......
......kssss.kkkkkkk.ssssssss.kkkkkkk.ssssk......
......ksssskgggggggksssssssskgggggggkssssk......
......ksssskgghhgggksssssssskgghhgggkssssk......
......ksssskgguuuugksssssssskgguuuugkssssk......
......ksssskgggggggksssssssskgggggggkssssk......
......kssss.kkkkkkk.ssssssss.kkkkkkk.ssssk......
......kssssssssssssssssnnnsssssssssssssssk......
......ksssssssssssssss.n.ssssssssssssssssk......
......kssssssssssssss.m.m.sssssssssssssssk......
......kssssssssssssssssssssssssssssssssssk......
.......kssssssssssssssssssssssssssssssssk.......
........kssstsssssssssssssssssssssstsssk........
.........kkssstsssssssssssssssssstsskkk.........
...........ksssssssssssssssssssssssk............
..........ksssssss..........ssssssssk...........
.........kssstss..............sssstssk..........
.........ksssss................ssssssk..........
..........ksssk................kssssk...........
...........kuuk................kuuk.............
............kk..................kk..............
""".strip("\n")

PALETTE = {
    "k": "#2c2c34",
    "s": "#d4d7de",
    "t": "#3d424c",
    "i": "#b4aea6",
    "g": "#e0a818",
    "u": "#1a1a22",
    "h": "#ffffff",
    "n": "#b08978",
    "m": "#4a4044",
}


def _render() -> Text:
    return render_sprite(SPRITE, PALETTE)


ICON = Icon(id="v1", title="银虎斑美短", render=_render)
