"""v2：同一只银虎斑美短，格子更小。v1 留着当备份。"""

from __future__ import annotations

from rich.text import Text

from cli.tui.icons.spec import Icon
from cli.tui.icons.sprite import render_sprite
from cli.tui.icons.v1 import PALETTE

# . 空  k 线  s 银毛  t 虎斑  i 耳内灰  g 金虹膜  u 瞳  h 高光  n 鼻  m 嘴
SPRITE = """
.........kkkk....kkkk.........
........kiiiik..kiiiik........
.......kisssskkkkssssik.......
......kssssssssssssssssk......
.....ksssstsstsstsssssssk.....
.....kssssstststssssssssk.....
....kss.kkkkk.ss.kkkkk.ssk....
....ksskgggggksskgggggkssk....
....ksskghuugksskghuugkssk....
....kss.kkkkk.ss.kkkkk.ssk....
....kssssssssnnnsssssssssk....
....ksssssss.m.m.ssssssssk....
....kssssssssssssssssssssk....
.....kssstsssssssssstsssk.....
......kksssssssssssssskk......
....kssssssss....ssssssssk....
...ksssstss........sstssssk...
....kssssk..........kssssk....
.....kuuk............kuuk.....
......kk..............kk......
""".strip("\n")


def _render() -> Text:
    return render_sprite(SPRITE, PALETTE)


ICON = Icon(id="v2", title="银虎斑美短", render=_render)
